name: Build and Release

# Se ejecuta cuando creas un nuevo tag v*.*.*
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-mac:
    name: Build macOS
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build macOS app
      run: |
        python build_scripts/build_mac.py --dmg --clean

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: |
          dist/TicketeraBuena.app
          dist/TicketeraBuena-*.dmg

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Windows app
      run: |
        python build_scripts/build_windows.py --clean

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: |
          dist/TicketeraBuena.exe

  create-release:
    name: Create Release
    needs: [build-mac, build-windows]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download macOS artifacts
      uses: actions/download-artifact@v3
      with:
        name: macos-build
        path: dist/

    - name: Download Windows artifacts
      uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: dist/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/TicketeraBuena-*.dmg
          dist/TicketeraBuena.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
