name: Build and Release

# Se ejecuta cuando creas un nuevo tag v*.*.*
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-mac:
    name: Build macOS
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install create-dmg
      run: |
        brew install create-dmg

    - name: Build macOS app
      run: |
        python build_scripts/build_mac.py --dmg --clean

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          dist/TicketeraBuena.app
          dist/TicketeraBuena-*.dmg

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Windows app
      run: |
        python build_scripts/build_windows.py --clean

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          dist/TicketeraBuena.exe

  create-release:
    name: Create Release
    needs: [build-mac, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-build
        path: macos-artifacts/

    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: windows-artifacts/

    - name: List downloaded files
      run: |
        echo "=== macOS artifacts ==="
        ls -lR macos-artifacts/
        echo "=== Windows artifacts ==="
        ls -lR windows-artifacts/
        echo "=== Find all files ==="
        find macos-artifacts/ -name "*.dmg"
        find windows-artifacts/ -name "*.exe"

    - name: Prepare release files
      run: |
        mkdir -p release-files
        find macos-artifacts/ -name "*.dmg" -exec cp {} release-files/ \;
        find windows-artifacts/ -name "*.exe" -exec cp {} release-files/ \;
        ls -lh release-files/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-files/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
